%YAML 1.2
---

Op_e:
  base: OperatorTemplate
  equations:
    - 'd/dt * r = delta/(PI * tau**2) + 2.*r*v/tau'
    - 'd/dt * i_e = v_e'
    - 'd/dt * v_e =  H_e/tau_e * (r_in_e + J*r) - i_e/tau_e^2. - 2.*v_e/tau_e'
    - 'd/dt * i_i = v_i'
    - 'd/dt * v_i =  H_i/tau_i * r_in_i - i_i/tau_i^2. - 2.*v_i/tau_i'
    - 'd/dt * eta = (eta_0 - eta - alpha*r)/tau_eta'
    - 'd/dt * v = (v**2 + eta + i_in + i_e - i_i) / tau - tau*(PI*r)**2'
  variables:
    r:
      default: output
    v:
      default: variable
    v_e:
      default: variable
    v_i:
      default: variable
    i_e:
      default: variable
    i_i:
      default: variable
    tau:
      default: 0.02
    tau_e:
      default: 0.01
    tau_i:
      default: 0.02
    H_e:
      default: 0.3
    H_i:
      default: 0.3
    J:
      default: 0.25
    delta:
      default: 1.0
    eta:
      default: variable
    eta_0:
      default: -2.5
    tau_eta:
      default: 0.1
    alpha:
      default: 0.05
    r_in_e:
      default: input
    r_in_i:
      default: input
    i_in:
      default: input

Op_i:
  base: OperatorTemplate
  equations:
    - 'd/dt * r = delta/(PI * tau**2) + 2.*r*v/tau'
    - 'd/dt * i_e = v_e'
    - 'd/dt * v_e =  H_e/tau_e * r_in_e - i_e/tau_e^2. - 2.*v_e/tau_e'
    - 'd/dt * i_i = v_i'
    - 'd/dt * v_i =  H_i/tau_i * (r_in_i + J*r) - i_i/tau_i^2. - 2.*v_i/tau_i'
    - 'd/dt * eta = (eta_0 - eta - alpha*r)/tau_eta'
    - 'd/dt * v = (v**2 + eta + i_in + i_e - i_i) / tau - tau*(PI*r)**2'
  variables:
    r:
      default: output
    v:
      default: variable
    v_e:
      default: variable
    v_i:
      default: variable
    i_e:
      default: variable
    i_i:
      default: variable
    tau:
      default: 0.02
    tau_e:
      default: 0.01
    tau_i:
      default: 0.02
    H_e:
      default: 0.3
    H_i:
      default: 0.3
    J:
      default: 0.25
    delta:
      default: 1.0
    eta:
      default: variable
    eta_0:
      default: -1.5
    tau_eta:
      default: 0.1
    alpha:
      default: 0.05
    r_in_e:
      default: input
    r_in_i:
      default: input
    i_in:
      default: input

Pop_e:
  base: NodeTemplate
  operators:
    - Op_e

Pop_i:
  base: NodeTemplate
  operators:
    - Op_i

DummyEdge:
  base: EdgeTemplate
  operators: []

EIC:
  base: CircuitTemplate
  nodes:
    PC: Pop_e
    IIN: Pop_i
  edges:
    - [PC/Op_e/r, IIN/Op_i/r_in_e, DummyEdge, {weight: 0.5}]
    - [IIN/Op_i/r, PC/Op_e/r_in_i, DummyEdge, {weight: 1.0}]

CMC:
  base: CircuitTemplate
  circuits:
    L3: EIC
    L5: EIC
  edges:
    - [L3/PC/Op_e/r, L5/IIN/Op_i/r_in_e, DummyEdge, {weight: 0.1}]
    - [L3/PC/Op_e/r, L5/PC/Op_e/r_in_e, DummyEdge, {weight: 0.1}]
    - [L5/PC/Op_e/r, L3/IIN/Op_i/r_in_e, DummyEdge, {weight: 0.1}]
